### ISSUE TITLE
Tolong diperbaiki halaman google developer nya

### ISSUE THREAD

**Issue by rizkiv1** [Arum18/Mobile#2]
Sesuai judul, Tolong diperbaiki halaman google developer nya. Kalau memang gak bisa silahkan balas. Soalnya saya bingung ini beneran punya anda atau bukan.

**Comment by BintiMukaromah** [comment]
Maaf kak, kemaren itu pinjem laptop temenku ngerjainnya, jadi kayaknya
salah kirim🙏

**Comment by ridwansulthoni** [comment]
> Sesuai judul, Tolong diperbaiki halaman google developer nya. Kalau memang gak bisa silahkan balas. Soalnya saya bingung ini beneran punya anda atau bukan.

Maaf sebelumnya kak baru saya balas, sudah saya perbaiki kak
https://developers.google.com/profile/u/104754294635186498997

**Comment by rizkiv1** [comment]
seeep
